CREATE TABLE user_activities
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    activity_type VARCHAR(100)                            NOT NULL,
    description   VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    icon          VARCHAR(50),
    CONSTRAINT pk_user_activities PRIMARY KEY (id)
);