CREATE TABLE payment (
                         id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         expense_id BIGINT NOT NULL,
                         name VARCHAR(255) NOT NULL,
                         status VARCHAR(10),
                         payment_date DATE,
                         CONSTRAINT fk_expense FOREIGN KEY(expense_id) REFERENCES expense(id)
);

ALTER TABLE payment ADD CONSTRAINT payment_expense_id_key UNIQUE (expense_id);