openapi: 3.0.3
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: user
  description: User operations
- name: saving
  description: All about your savings
paths:
  /api/v1/users/{id}:
    get:
      tags:
      - user
      summary: Get user by id
      operationId: getUserById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDTO"
        "404":
          description: Not found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDTO"
    put:
      tags:
      - user
      summary: Update user
      operationId: updateUser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDTO"
        required: true
      responses:
        "200":
          description: Updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDTO"
        "404":
          description: Not found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDTO"
    delete:
      tags:
      - user
      summary: Delete user
      operationId: deleteUser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDTO"
        "404":
          description: Not found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDTO"
  /api/v1/savings/{savingId}:
    get:
      tags:
      - saving
      summary: Get saving by ID
      description: Returns a single saving
      operationId: getSavingById
      parameters:
      - name: savingId
        in: path
        description: ID of saving to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Saving found
          content:
            '*/*':
              schema:
                type: object
        "404":
          description: Saving not found
          content:
            '*/*':
              schema:
                type: object
    put:
      tags:
      - saving
      summary: Update an existing saving by ID
      operationId: updateSaving
      parameters:
      - name: savingId
        in: path
        description: ID of saving to update
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: Updated saving
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SavingDTO"
        required: true
      responses:
        "200":
          description: Saving updated
          content:
            '*/*':
              schema:
                type: object
        "400":
          description: ID mismatch
          content:
            '*/*':
              schema:
                type: object
        "404":
          description: Saving not found
          content:
            '*/*':
              schema:
                type: object
    delete:
      tags:
      - saving
      summary: Delete a saving by ID
      operationId: deleteSaving
      parameters:
      - name: savingId
        in: path
        description: ID of saving to delete
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: Saving deleted
          content:
            '*/*':
              schema:
                type: object
        "404":
          description: Saving not found
          content:
            '*/*':
              schema:
                type: object
  /api/v1/payments/{id}:
    get:
      tags:
      - payment-controller
      operationId: getById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    put:
      tags:
      - payment-controller
      operationId: update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    delete:
      tags:
      - payment-controller
      operationId: delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/v1/incomes/{id}:
    get:
      tags:
      - income-controller
      operationId: getIncomeById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/IncomeDTO"
    put:
      tags:
      - income-controller
      operationId: updateIncome
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IncomeDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/IncomeDTO"
    delete:
      tags:
      - income-controller
      operationId: deleteIncome
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
  /api/v1/expenses/{id}:
    get:
      tags:
      - expense-controller
      operationId: getExpenseById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ExpenseDTO"
    put:
      tags:
      - expense-controller
      operationId: updateExpense
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExpenseDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ExpenseDTO"
    delete:
      tags:
      - expense-controller
      operationId: deleteExpense
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
  /api/v1/users:
    get:
      tags:
      - user
      summary: Get users
      operationId: getUsers
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDTO"
    post:
      tags:
      - user
      summary: Create user
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDTO"
        required: true
      responses:
        "200":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDTO"
  /api/v1/savings:
    get:
      tags:
      - saving
      summary: Get all savings
      description: Returns all available savings
      operationId: getAllSavings
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    post:
      tags:
      - saving
      summary: Add a new saving
      operationId: addSaving
      requestBody:
        description: Saving to add
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SavingDTO"
            examples:
              SavingExample:
                description: SavingExample
                value:
                  amount: 10000.0
                  date: 2025-09-04T10:47:00+00:00
                  goal: Apartament
                  description: My dream apartament
              BadExample:
                description: BadExample
                value:
                  amount: -2000.0
                  date: 2222-09-04T10:47:00+00:00
                  goal: ""
                  description: bad description
        required: true
      responses:
        "200":
          description: Saving added successfully
          content:
            '*/*':
              schema:
                type: object
        "400":
          description: Invalid input
          content:
            '*/*':
              schema:
                type: object
  /api/v1/payments:
    get:
      tags:
      - payment-controller
      operationId: getAll
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PaymentDTO"
    post:
      tags:
      - payment-controller
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/v1/incomes:
    get:
      tags:
      - income-controller
      operationId: getAllIncomes
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/IncomeDTO"
    post:
      tags:
      - income-controller
      operationId: createIncome
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IncomeDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/IncomeDTO"
  /api/v1/expenses:
    get:
      tags:
      - expense-controller
      operationId: getAllExpenses
      parameters:
      - name: userId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ExpenseDTO"
    post:
      tags:
      - expense-controller
      operationId: addExpense
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExpenseDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ExpenseDTO"
  /test:
    get:
      tags:
      - test-controller
      operationId: testEndpoint
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: string
  /api/v1/users/by-email:
    get:
      tags:
      - user
      summary: Get user by email
      operationId: getUserByEmail
      parameters:
      - name: email
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDTO"
        "404":
          description: Not found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDTO"
components:
  schemas:
    UserDTO:
      type: object
      description: User DTO
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        name:
          type: string
          description: Full name
          example: Andrei
        email:
          type: string
          description: Email address
          example: andrei@gmail.com
        password:
          type: string
          description: Password
          example: password
        createdAt:
          type: string
          format: date-time
          description: 'Account creation timestamp '
          example: 2025-09-24T14:35:00
        balance:
          type: number
          description: Account balance
          example: 1500.75
    SavingDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        amount:
          type: number
        date:
          type: string
          format: date-time
        goal:
          type: string
        description:
          type: string
    PaymentDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        amount:
          type: number
        frequency:
          type: string
          enum:
          - ONE_TIME
          - MONTHLY
          - YEARLY
        nextDueDate:
          type: string
          format: date-time
        isActive:
          type: boolean
    IncomeDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        amount:
          type: number
        source:
          type: string
        date:
          type: string
          format: date-time
        description:
          type: string
    ExpenseDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        amount:
          type: number
        category:
          type: string
          maxLength: 50
          minLength: 1
        date:
          type: string
          format: date
        description:
          type: string
          maxLength: 200
          minLength: 0
      required:
      - amount
      - category
      - date
      - userId
